"""empty message

Revision ID: 70bc878e1fb6
Revises: f6a1bf477cf7
Create Date: 2022-02-13 16:54:41.081574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bc878e1fb6'
down_revision = 'f6a1bf477cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('losses', sa.Integer(), nullable=True))
    op.drop_constraint('user_join_pokemon_poke_id_fkey', 'user_join_pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'user_join_pokemon', 'pokemon', ['poke_id'], ['poke_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_join_pokemon', type_='foreignkey')
    op.create_foreign_key('user_join_pokemon_poke_id_fkey', 'user_join_pokemon', 'pokemon', ['poke_id'], ['poke_id'])
    op.drop_column('user', 'losses')
    op.drop_column('user', 'wins')
    # ### end Alembic commands ###
